Added EventForwarding Playground Files
CrowdStrike/logscale-community-content pull request #9
Opened 2023-03-14 01:03 UTC by nthnthcandrew

2023-03-22 18:16 UTC, nlabadie-crwd commented
Let's switch this to URLs instead of binaries.

2023-03-24 14:14 UTC, nlabadie-crwd requested changes
Let's change the references based on our previous discussion.

2023-03-28 02:00 UTC, nthnthcandrew commented
Changes have been made. Removed binaries and renamed yaml file.

2023-04-10 18:15 UTC, nlabadie-crwd approved these changes

2023-04-10 18:15 UTC, merged